### ISSUE TITLE
node-gyp rebuild error?

### ISSUE THREAD

**Issue by mengjian-github** [yoshoku/hnswlib-node#66]
<img width="179" alt="image" src="https://user-images.githubusercontent.com/8306959/230958320-3f9e24e2-9ac2-4258-890b-89c80f7de19b.png">

{"time":1681147316100,"hostname":"6431b4565cfa36c45b618ba6","pid":31376,"level":"error","name":"pnpm","code":"ELIFECYCLE","errno":1,"pkgid":"hnswlib-node@1.4.2","stage":"install","script":"node-gyp rebuild","pkgname":"hnswlib-node","name":"pnpm","err":{"name":"pnpm","message":"hnswlib-node@1.4.2 install: `node-gyp rebuild`\nExit status 1","code":"ELIFECYCLE","stack":"pnpm: hnswlib-node@1.4.2 install: `node-gyp rebuild`\nExit status 1\n    at EventEmitter.<anonymous> (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:99653:17)\n    at EventEmitter.emit (node:events:513:28)\n    at ChildProcess.<anonymous> (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:83511:18)\n    at ChildProcess.emit (node:events:513:28)\n    at maybeClose (node:internal/child_process:1091:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:302:5)"}}

**Comment by mengjian-github** [comment]
make is not installed.
