### ISSUE TITLE
Running into an issue when trying to install hnswlib-node with npm

### ISSUE THREAD

**Issue by kac487** [yoshoku/hnswlib-node#76]
Hello, I am running into this error when attempting to install hnswlib-node

```
>> npm install hnswlib-node   
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:@types/emotion/cache

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kac487/.npm/_logs/2023-04-21T02_29_33_748Z-debug-0.log
```

Here are the details from the  contents of the log file referenced above 

```
...
...
227 timing idealTree Completed in 18918ms
228 timing command:install Completed in 18925ms
229 verbose stack Error: Unsupported URL Type "link:": link:@types/emotion/cache
229 verbose stack     at unsupportedURLType (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:327:15)
229 verbose stack     at fromURL (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:387:13)
229 verbose stack     at Function.resolve (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
229 verbose stack     at [nodeFromEdge] (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1058:22)
229 verbose stack     at [buildDepStep] (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:36)
229 verbose stack     at async Arborist.buildIdealTree (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
229 verbose stack     at async Promise.all (index 1)
229 verbose stack     at async Arborist.reify (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
229 verbose stack     at async Install.exec (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/lib/commands/install.js:146:5)
229 verbose stack     at async module.exports (/home/kac487/.nvm/versions/node/v18.15.0/lib/node_modules/npm/lib/cli.js:134:5)
230 verbose cwd /home/kac487/dev/project/repos/projectDirectory
231 verbose Linux 5.19.0-40-generic
232 verbose node v18.15.0
233 verbose npm  v9.5.0
234 error code EUNSUPPORTEDPROTOCOL
235 error Unsupported URL Type "link:": link:@types/emotion/cache
236 verbose exit 1
237 timing npm Completed in 18951ms
238 verbose unfinished npm timer reify 1682044173773
239 verbose unfinished npm timer reify:loadTrees 1682044173776
240 verbose unfinished npm timer idealTree:buildDeps 1682044173789
241 verbose unfinished npm timer idealTree:#root 1682044173789
242 verbose code 1
243 error A complete log of this run can be found in:
243 error     /home/kac487/.npm/_logs/2023-04-21T02_29_33_748Z-debug-0.log
```

I've tried using npm and pnpm to install hnswlib-node but i haven't had any luck with either. Any help would be greatly appreciated.

**Comment by yoshoku** [comment]
@kac487 
You may want to check your `package.json`. NPM does not support `link` keyword, on the other hand, Yarn supports it.
https://stackoverflow.com/questions/74679689/unsupported-url-type-link-while-using-npm

I think that you can avoid that error by changing the `link` keyword to the `file` keyword or using Yarn.

**Comment by raselSoftNode** [comment]
@kac487  did you find any solution?
